### ISSUE TITLE
SPA Mode support

### ISSUE THREAD

**Issue by JoshZA** [ptkdev/sveltekit-cordova-adapter#1]
Hey @ptkdev 

Thanks for the great work on this.

Do you plan to add SPA support in the future?

Thanks,

**Comment by ptkdev** [comment]
Cordova/Capacitor run an index.html file, the problem happen with the router: svelte creates the url routes with absolute path (example: /page2).

Absolute paths only work if they run app on a webserver, but Capacitor/Cordova don’t support native webserver (at least that’s how I understand).

So it is possible to use a single page app only for the home page and only if the router does not change the page url from `/index.html` to `/page2`

Probably no, we can't support SPA at moment.

**Comment by JoshZA** [comment]
Makes sense, thank you
